### ISSUE TITLE
create_html_bracket fails when playoff brackets do not exist

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#145]
**Describe the bug**
Prediction routing test throws an error for 2021 due to lack of playoff data.
https://github.com/skekre98/NBA-Search/blob/0bb22568befaf307fd13ce0d2036fd66fb6d150f/modules/scraper.py#L26-L27
The error is arising from the year now being set to 2021.

**To Reproduce**
1. Run tests
```
$ python main test
```
2. See error
```
Traceback (most recent call last):
  File "/home/circleci/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/circleci/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/circleci/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/circleci/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/circleci/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/circleci/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/circleci/project/app.py", line 95, in predictions
    bracket = create_html_bracket(bracket)
  File "/home/circleci/project/modules/transformer.py", line 104, in create_html_bracket
    wf = west[-1][0]
IndexError: list index out of range
F
======================================================================
FAIL: test_predictions_routing (tests.flask_tests.TestRouting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/tests/flask_tests.py", line 95, in test_predictions_routing
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200
```

**Expected behavior**
Expects `200` response.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a
 - Version: latest

**Additional context**
The fix will likely simply require a check to see if playoff brackets are empty. If this is the case, just return an empty playoff map:
```python
playoff_map = {
        "wc1" : [],
        "wc2" : [],
        "wcf" : [],
        "ec1" : [],
        "ec2" : [],
        "ecf" : [],
        "f" : []
    }
```

**Comment by MishalAshraf** [comment]
New to working on open source projects so please bear with me! I tried to do start working on this issue, following the steps outlined in the Contributing Guideline. I got the following error: 

<img width="1309" alt="Screen Shot 2021-01-05 at 3 13 57 PM" src="https://user-images.githubusercontent.com/53178950/103709965-a518ef80-4f68-11eb-9597-f813eef4ef85.png">

I got a similar error when working with sklearn in a completely different virtual env. Any clue what's going on here?

**Comment by skekre98** [comment]
Hi @MishalAshraf, thanks for looking into this! I can't say what is going on for certain at first glance, but it seems to me you are running an older version of `python` and `pip`. You can check what versions you are on with the following commands.
```
$ pip --version
pip 20.3.3 from $HOME/opt/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
$ python --version
Python 3.7.6
``` 
This project requires you to be running python3.5+. Let me know if you would like me to assign this issue over to you 😄

**Comment by MishalAshraf** [comment]
Thanks @skekre98 , I figured out my issue. 

I updated the create_html_bracket function as suggested above. I am getting a type error which seems to be related to the playoff_map being populated with NoneTypes as opposed to numbers or a string. Thoughts on this?

**Comment by skekre98** [comment]
Hi @MishalAshraf, I am unsure about the first issue, but to fix the second issue can you add a null pointer check on line 189 in scraper:
https://github.com/skekre98/NBA-Search/blob/0bb22568befaf307fd13ce0d2036fd66fb6d150f/modules/scraper.py#L189
Should look something like this:
```python
if stat["data-stat"] == "per" and stat.string:
    per = float(stat.string)
```

Yes, please open up a PR with these changes. It would be easier to work on the fix from there 👍

**Comment by MishalAshraf** [comment]
<img width="717" alt="Screen Shot 2021-01-05 at 4 14 12 PM" src="https://user-images.githubusercontent.com/53178950/103826966-bfb49c80-502c-11eb-9acd-c98808bb47b4.png">

Sure, see photo for screen shot! 
Updated and added PR.

**Comment by skekre98** [comment]
@MishalAshraf my apologies, I see the issue now. The html templates are still referencing indices in the playoff bracket. Instead of returning an empty playoff map, we will need to return a playoff map populated by empty strings. We can insert it after this line:
https://github.com/skekre98/NBA-Search/blob/0bb22568befaf307fd13ce0d2036fd66fb6d150f/modules/transformer.py#L94-L95

The code will look something like this:
```python
if not west and not east:
    # empty mapping of playoff bracket
    void_map = {
        "wc1" : [[("",""), ("","")], [("",""), ("","")], [("",""), ("","")], [("",""), ("","")]], 
        "wc2" : [[("",""), ("","")], [("",""), ("","")]],
        "wcf" : [[("",""), ("","")]],
        "ec1" : [[("",""), ("","")], [("",""), ("","")], [("",""), ("","")], [("",""), ("","")]], 
        "ec2" : [[("",""), ("","")], [("",""), ("","")]],
        "ecf" : [[("",""), ("","")]],
        "f" : [[("",""), ("","")]]
    }
    return void_map
```

Apologies for the misunderstanding 😅

**Comment by MishalAshraf** [comment]
@skekre98 sure, I can update this! I wonder if we can adjust in a way that will handle the adjusted playoff tournament situation going on this year?

**Comment by skekre98** [comment]
> I wonder if we can adjust in a way that will handle the adjusted playoff tournament situation going on this year?

@MishalAshraf can you elaborate on this? Will the playoffs be different this year than previous years?

**Comment by MishalAshraf** [comment]
`[2021-01-06 21:17:10,857] ERROR in app: Exception on /predictions [GET]
Traceback (most recent call last):
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mishal/Documents/dev/NBA-Search/NBA-Search/app.py", line 98, in predictions
    return render_template("predictions.html", bracket=bracket, west_standings=west_standings, east_standings=east_standings)
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/mishal/Documents/dev/NBA-Search/NBA-Search/templates/predictions.html", line 181, in top-level template code
    <li class="team team-bottom">{{ bracket["f"][1][0] }}<span
  File "/Users/mishal/Documents/dev/NBA-Search/tutorial-env/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]`

Actually tried to solve this one now that I am a bit more familiar with how the flask app works. I tried both tuple and list structures for the internal data holders and got the same error. Thoughts? @skekre98

**Comment by skekre98** [comment]
@MishalAshraf can you try changing the finals entry from `"f" : [[("",""), ("","")]]` to `"f" : [("",""), ("","")]`. I think it might be an index issue. Also did you receive this error when running the tests or the actual app?

**Comment by MishalAshraf** [comment]
I applied this. running tests showed no errors. running the app and going to predictions also rendered. It seems however that they updated the bracket now. 
<img width="1174" alt="Screen Shot 2021-01-07 at 3 32 22 PM" src="https://user-images.githubusercontent.com/53178950/103956658-df67c580-50fd-11eb-8fec-78fde3260e77.png">

**Comment by skekre98** [comment]
>  It seems however that they updated the bracket now.

@MishalAshraf can you elaborate on this?
