### ISSUE TITLE
Having trouble downloading dependencies

### ISSUE THREAD

**Issue by shirleyp1097** [skekre98/NBA-Search#155]
When I run the ./setup.sh in my Mac terminal , I get back the following error:

Collecting pandas>=0.24.2
  Using cached pandas-1.2.4-cp39-cp39-macosx_10_9_x86_64.whl (10.7 MB)
ERROR: Could not find a version that satisfies the requirement scikit-learn==0.22.2
ERROR: No matching distribution found for scikit-learn==0.22.2
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: No module named spacy
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: No module named spacy
Traceback (most recent call last):
  File "/Users/*-/NBA-Search/query_classifier.py", line 3, in <module>
    from modules.transformer import predictors, query_tokenizer
  File "/Users/*-/NBA-Search/modules/transformer.py", line 2, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'

I've downloaded scikit-learn separately. Perhaps it's due to the syntax of "scikit-learn==0.22.2" when perhaps that's an outdated version? Any advice would be greatly appreciated.

**Comment by skekre98** [comment]
Hi @shirleyp1097, I am unfortunately unable to reproduce your issue:
```
(base) C02C84Q2LVDL:~ sharvil.kekre$ pip --version
pip 20.0.2 from /Users/sharvil.kekre/opt/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
(base) C02C84Q2LVDL:~ sharvil.kekre$ pip install scikit-learn==0.22.2
Collecting scikit-learn==0.22.2
  Using cached scikit_learn-0.22.2-cp37-cp37m-macosx_10_9_x86_64.whl (7.1 MB)
Requirement already satisfied: numpy>=1.11.0 in ./opt/anaconda3/lib/python3.7/site-packages (from scikit-learn==0.22.2) (1.18.1)
Requirement already satisfied: scipy>=0.17.0 in ./opt/anaconda3/lib/python3.7/site-packages (from scikit-learn==0.22.2) (1.4.1)
Requirement already satisfied: joblib>=0.11 in ./opt/anaconda3/lib/python3.7/site-packages (from scikit-learn==0.22.2) (0.14.1)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.0
    Uninstalling scikit-learn-0.24.0:
      Successfully uninstalled scikit-learn-0.24.0
Successfully installed scikit-learn-0.22.2
(base) C02C84Q2LVDL:~ sharvil.kekre$ pip install spacy
Collecting spacy
  Downloading spacy-3.0.5-cp37-cp37m-macosx_10_9_x86_64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 2.9 MB/s 
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.5-cp37-cp37m-macosx_10_9_x86_64.whl (31 kB)
Collecting catalogue<2.1.0,>=2.0.1
  Downloading catalogue-2.0.2-py3-none-any.whl (9.6 kB)
Collecting pydantic<1.8.0,>=1.7.1
  Downloading pydantic-1.7.3-cp37-cp37m-macosx_10_9_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 24.8 MB/s 
Collecting spacy-legacy<3.1.0,>=3.0.0
  Downloading spacy_legacy-3.0.2-py2.py3-none-any.whl (7.8 kB)
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.5-cp37-cp37m-macosx_10_9_x86_64.whl (104 kB)
     |████████████████████████████████| 104 kB 27.5 MB/s 
Requirement already satisfied: numpy>=1.15.0 in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (1.18.1)
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.5-cp37-cp37m-macosx_10_9_x86_64.whl (18 kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (2.22.0)
Collecting srsly<3.0.0,>=2.4.0
  Downloading srsly-2.4.1-cp37-cp37m-macosx_10_9_x86_64.whl (449 kB)
     |████████████████████████████████| 449 kB 26.1 MB/s 
Collecting blis<0.8.0,>=0.4.0
  Downloading blis-0.7.4-cp37-cp37m-macosx_10_9_x86_64.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 16.2 MB/s 
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (1.5.0)
Collecting pathy>=0.3.5
  Downloading pathy-0.4.0-py3-none-any.whl (36 kB)
Collecting typing-extensions<4.0.0.0,>=3.7.4; python_version < "3.8"
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting wasabi<1.1.0,>=0.8.1
  Downloading wasabi-0.8.2-py3-none-any.whl (23 kB)
Requirement already satisfied: packaging>=20.0 in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (20.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (4.42.1)
Collecting typer<0.4.0,>=0.3.0
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
Collecting thinc<8.1.0,>=8.0.2
  Downloading thinc-8.0.2-cp37-cp37m-macosx_10_9_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 22.3 MB/s 
Requirement already satisfied: setuptools in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (44.0.0)
Requirement already satisfied: jinja2 in ./opt/anaconda3/lib/python3.7/site-packages (from spacy) (2.11.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./opt/anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./opt/anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in ./opt/anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.8)
Requirement already satisfied: zipp>=0.5 in ./opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->spacy) (2.2.0)
Collecting smart-open<4.0.0,>=2.2.0
  Downloading smart_open-3.0.0.tar.gz (113 kB)
     |████████████████████████████████| 113 kB 23.5 MB/s 
Requirement already satisfied: six in ./opt/anaconda3/lib/python3.7/site-packages (from packaging>=20.0->spacy) (1.14.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./opt/anaconda3/lib/python3.7/site-packages (from packaging>=20.0->spacy) (2.4.6)
Collecting click<7.2.0,>=7.1.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: MarkupSafe>=0.23 in ./opt/anaconda3/lib/python3.7/site-packages (from jinja2->spacy) (1.1.1)
Building wheels for collected packages: smart-open
  Building wheel for smart-open (setup.py) ... done
  Created wheel for smart-open: filename=smart_open-3.0.0-py3-none-any.whl size=107097 sha256=952cc88e333f554f5fa7a1bda1c146f7d2ffb6d20cf7c187df3d1d96e22ae41a
  Stored in directory: /Users/sharvil.kekre/Library/Caches/pip/wheels/83/a6/12/bf3c1a667bde4251be5b7a3368b2d604c9af2105b5c1cb1870
Successfully built smart-open
Installing collected packages: cymem, catalogue, pydantic, spacy-legacy, murmurhash, preshed, srsly, blis, click, typer, smart-open, pathy, typing-extensions, wasabi, thinc, spacy
  Attempting uninstall: click
    Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
Successfully installed blis-0.7.4 catalogue-2.0.2 click-7.1.2 cymem-2.0.5 murmurhash-1.0.5 pathy-0.4.0 preshed-3.0.5 pydantic-1.7.3 smart-open-3.0.0 spacy-3.0.5 spacy-legacy-3.0.2 srsly-2.4.1 thinc-8.0.2 typer-0.3.2 typing-extensions-3.7.4.3 wasabi-0.8.2
``` 

I notice you are running this on python3.9. Perhaps try setting the repo up with 3.7 or 3.6. These are the version that this codebase has been built on and tested with.
