### ISSUE TITLE
test_get_adv_stats is failing from NoneType object

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#159]
**Describe the bug**
`test_get_adv_stats` is failing, seems to be from a missing div when scraping advanced stats. 

**To Reproduce**
1. Setup the environment with `./setup.sh`
2. Run `python main.py test` to run unit tests
3. See error
```
ERROR: test_get_adv_stats (tests.module_tests.TestScraper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/tests/module_tests.py", line 107, in test_get_adv_stats
    stat = scraper.get_adv_stat(random_name, random_stat)
  File "/home/circleci/project/modules/scraper.py", line 288, in get_adv_stat
    comments = advanced_div.find_all(string=lambda text: isinstance(text, Comment))[0]
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Expected behavior**
This should correctly scrape the advanced of NBA players and check for any NoneType objects in case there is an error in scraping or something is removed in the future.

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
This is setup agnostic the issue was found during CircleCI tests.

**Comment by AColocho** [comment]
You can assign this issue to me. I'll review it in the next couple of days.

**Comment by skekre98** [comment]
Awesome, thanks @AColocho

**Comment by AColocho** [comment]
@skekre98 I found the issue. Basketball Reference removed the comment that was used as an anchor to find the table. I'm having trouble understand what the function returns. Is it just the latest stat as a float? or is it all the available stats for the category as a list of floats?

**Comment by skekre98** [comment]
Hi @AColocho, the function should be returning the advanced statistic as a float value. The user will specify the name of the player and the advanced statistic to retrieve when calling the function. For example:
```python
stat = scraper.get_adv_stat("Kobe Bryant", "defensive box plus/minus")
```

**Comment by dominikk12** [comment]
is this issue done or not, i would like to do on it

**Comment by AColocho** [comment]
Issue is done. It's waiting code review and merge.
